
---
- name: Playbook para instalar la pila LAMP en el FrontEnd
  hosts: frontend
  become: yes

  tasks:
    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    - name: Instalar el servidor web Apache
      apt:
        name: apache2
        state: present

    - name: Instalar PHP y los módulos necesarios
      apt: 
        name:
          - php
          - php-mysql
          - libapache2-mod-php
        state: present
     
    - name: Habilitar el módulo rewrite de Apache
      apache2_module:
        name: rewrite
        state: present

    - name: Copiamos el archivo de configuración de PHP
      copy:
        src: /home/ubuntu/PRACTICA-IAW-3/moodle/php/index.php
        dest: /var/www/html/index.php
        mode: 0755

    - name: Cambiar el propietario y grupo del directorio de Apache
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
